# Desktop Info by Glenn Delahoy
# This demonstrates how you might set up a corporate machine using absolute positioning
# Desktop Info takes up the entire monitor by setting width and height to 0
# You can then position the logo anywhere on the screen
# And some basic support info and a quick hyperlink anywhere else on the screen.

[options]
top=0
left=0
width=0
height=0
contextmenu=0
allowdrag=0

[items]

# colors
set White   = #ffffff
set Grey    = #909090

# corporate logo
IMAGE=xr:5,yb:70,align:r,file:images/LOGONAME.jpg,width:90


# info and support hyperlink in bottom right corner
FONT-FACE=Verdana
COLOR=%yellow%
USER=set:username,onload:1,hidden:1,background-interval:3600
HOST=set:hostname,onload:1,hidden:1,background-interval:3600
COMMENT=xr:2,yb:48,align:r,font-size:10,display:%hostname%/%username%
ALLIPADDRESS=xr:2,yb:34,align:r,font-size:10,active:1,interval:30,activeonly:1,multirow:0,display:%1

